name: Gitee 2 Github

on:
  schedule:
    # 每10分钟同步一次
    - cron:  '*/10 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Mirror the gitee repos to github.
      uses: Yikun/hub-mirror-action@master
      with:
        src: gitee/whitewatercn
        dst: github/whitewatercn
        dst_key: ${{ secrets.SYNC__PRIVATE_KEY }}
        dst_token:  ${{ secrets.SYNC_TOKEN }}
        static_list: "great-doctor"
        force_update: true
        debug: true
